/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.97
 * Generated at: 2024-12-20 10:34:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.genuine.model.User;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.genuine.model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    User user = (User) session.getAttribute("user");
    if(user == null) {
        response.sendRedirect("login.jsp");
        return;
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Genuine - Electronics Store</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            font-family: 'Arial', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        :root {\r\n");
      out.write("            --primary-color: #000000;\r\n");
      out.write("            --secondary-color: #ffffff;\r\n");
      out.write("            --accent-color: #333333;\r\n");
      out.write("            --hover-color: #555555;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            background-color: var(--secondary-color);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Navigation Bar */\r\n");
      out.write("        .navbar {\r\n");
      out.write("            background-color: var(--primary-color);\r\n");
      out.write("            padding: 1rem 2rem;\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            z-index: 1000;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-container {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo {\r\n");
      out.write("            color: var(--secondary-color);\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-links {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-links a {\r\n");
      out.write("            color: var(--secondary-color);\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            transition: color 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-links a:hover {\r\n");
      out.write("            color: #cccccc;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-icon {\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Search Bar */\r\n");
      out.write("        .search-container {\r\n");
      out.write("            margin-top: 80px;\r\n");
      out.write("            padding: 1rem 2rem;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-bar {\r\n");
      out.write("            max-width: 600px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 0.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-input {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            padding: 0.8rem;\r\n");
      out.write("            border: 2px solid var(--primary-color);\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-button {\r\n");
      out.write("            padding: 0.8rem 1.5rem;\r\n");
      out.write("            background-color: var(--primary-color);\r\n");
      out.write("            color: var(--secondary-color);\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: background-color 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-button:hover {\r\n");
      out.write("            background-color: var(--hover-color);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Popular Section */\r\n");
      out.write("        .popular-section {\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .section-title {\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("            color: var(--primary-color);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .popular-grid {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));\r\n");
      out.write("            gap: 1rem;\r\n");
      out.write("            margin-bottom: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .popular-item {\r\n");
      out.write("            background-color: #f5f5f5;\r\n");
      out.write("            height: 200px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("            color: #888;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Categories Section */\r\n");
      out.write("        .categories-section {\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .category-grid {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));\r\n");
      out.write("            gap: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .category-card {\r\n");
      out.write("            background-color: var(--secondary-color);\r\n");
      out.write("            border: 1px solid #eee;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            padding: 1rem;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: transform 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .category-card:hover {\r\n");
      out.write("            transform: translateY(-5px);\r\n");
      out.write("            box-shadow: 0 5px 15px rgba(0,0,0,0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .category-icon {\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("            color: var(--primary-color);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .category-name {\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("            color: var(--primary-color);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Responsive Design */\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .nav-container {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                gap: 1rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .nav-links {\r\n");
      out.write("                flex-wrap: wrap;\r\n");
      out.write("                justify-content: center;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .search-container {\r\n");
      out.write("                margin-top: 120px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .popular-grid,\r\n");
      out.write("            .category-grid {\r\n");
      out.write("                grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Navigation Bar -->\r\n");
      out.write("    <nav class=\"navbar\">\r\n");
      out.write("        <div class=\"nav-container\">\r\n");
      out.write("            <a href=\"#\" class=\"logo\">Genuine</a>\r\n");
      out.write("            <div class=\"nav-links\">\r\n");
      out.write("                <a href=\"#\"><i class=\"fas fa-home\"></i> Home</a>\r\n");
      out.write("                <a href=\"#\"><i class=\"fas fa-shopping-bag\"></i> Orders</a>\r\n");
      out.write("                <a href=\"#\"><i class=\"fas fa-wallet\"></i> Balance</a>\r\n");
      out.write("                <a href=\"#\"><i class=\"fas fa-info-circle\"></i> About</a>\r\n");
      out.write("                <a href=\"#\" class=\"user-icon\"><i class=\"fas fa-user-circle\"></i></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <!-- Search Bar -->\r\n");
      out.write("    <div class=\"search-container\">\r\n");
      out.write("        <div class=\"search-bar\">\r\n");
      out.write("            <input type=\"text\" class=\"search-input\" placeholder=\"Search for products...\">\r\n");
      out.write("            <button class=\"search-button\"><i class=\"fas fa-search\"></i> Search</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Popular Section -->\r\n");
      out.write("    <section class=\"popular-section\">\r\n");
      out.write("        <h2 class=\"section-title\">Popular Products</h2>\r\n");
      out.write("        <div class=\"popular-grid\">\r\n");
      out.write("            <div class=\"popular-item\">Popular Item 1</div>\r\n");
      out.write("            <div class=\"popular-item\">Popular Item 2</div>\r\n");
      out.write("            <div class=\"popular-item\">Popular Item 3</div>\r\n");
      out.write("            <div class=\"popular-item\">Popular Item 4</div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Categories Section -->\r\n");
      out.write("    <section class=\"categories-section\">\r\n");
      out.write("        <h2 class=\"section-title\">Product Categories</h2>\r\n");
      out.write("        <div class=\"category-grid\">\r\n");
      out.write("            <div class=\"category-card\">\r\n");
      out.write("                <div class=\"category-icon\"><i class=\"fas fa-mobile-alt\"></i></div>\r\n");
      out.write("                <div class=\"category-name\">Mobile Phones</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"category-card\">\r\n");
      out.write("                <div class=\"category-icon\"><i class=\"fas fa-laptop\"></i></div>\r\n");
      out.write("                <div class=\"category-name\">Laptops & PCs</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"category-card\">\r\n");
      out.write("                <div class=\"category-icon\"><i class=\"fas fa-watch\"></i></div>\r\n");
      out.write("                <div class=\"category-name\">Smart Watches</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"category-card\">\r\n");
      out.write("                <div class=\"category-icon\"><i class=\"fas fa-headphones\"></i></div>\r\n");
      out.write("                <div class=\"category-name\">Headphones</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"category-card\">\r\n");
      out.write("                <div class=\"category-icon\"><i class=\"fas fa-ear-listen\"></i></div>\r\n");
      out.write("                <div class=\"category-name\">Earpods</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"category-card\">\r\n");
      out.write("                <div class=\"category-icon\"><i class=\"fas fa-tv\"></i></div>\r\n");
      out.write("                <div class=\"category-name\">TVs</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        // Add click handlers for category cards\r\n");
      out.write("        document.querySelectorAll('.category-card').forEach(card => {\r\n");
      out.write("            card.addEventListener('click', () => {\r\n");
      out.write("                const category = card.querySelector('.category-name').textContent;\r\n");
      out.write("                // Add your category navigation logic here\r\n");
      out.write("                console.log(`Navigating to ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`);\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Add search functionality\r\n");
      out.write("        document.querySelector('.search-button').addEventListener('click', () => {\r\n");
      out.write("            const searchTerm = document.querySelector('.search-input').value;\r\n");
      out.write("            // Add your search logic here\r\n");
      out.write("            console.log(`Searching for: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${searchTerm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`);\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
